/**
 * Database types for TakaKori.
 *
 * Generated by hand from the live schema on 2026-10-01, verified against
 * information_schema. Regenerate with:
 *
 *   npx supabase gen types src/types/database.ts --lang typescript --linked
 *
 * (requires `npx supabase login` first)
 *
 * Note that `amount` and `opening_balance` are `numeric` in Postgres, which
 * crosses PostgREST as a **string**. The generated types say `number` because
 * supabase-js models numeric that way, so the real wire type is `string` —
 * see src/lib/money.ts. Treat money with the helpers there, never as a number.
 */

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[]

export type Database = {
  public: {
    Tables: {
      accounts: {
        Row: {
          id: string
          workspace_id: string
          name: string
          kind: string
          opening_balance: number
          is_archived: boolean
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          workspace_id: string
          name: string
          kind?: string
          opening_balance?: number
          is_archived?: boolean
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          workspace_id?: string
          name?: string
          kind?: string
          opening_balance?: number
          is_archived?: boolean
          created_at?: string
          updated_at?: string
        }
        Relationships: []
      }

      categories: {
        Row: {
          id: string
          workspace_id: string
          name: string
          type: string
          icon: string | null
          is_system: boolean
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          workspace_id: string
          name: string
          type: string
          icon?: string | null
          is_system?: boolean
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          workspace_id?: string
          name?: string
          type?: string
          icon?: string | null
          is_system?: boolean
          created_at?: string
          updated_at?: string
        }
        Relationships: []
      }

      profiles: {
        Row: {
          id: string
          full_name: string | null
          timezone: string
          currency: string
          locale: string
          created_at: string
          updated_at: string
        }
        Insert: {
          id: string
          full_name?: string | null
          timezone?: string
          currency?: string
          locale?: string
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          full_name?: string | null
          timezone?: string
          currency?: string
          locale?: string
          created_at?: string
          updated_at?: string
        }
        Relationships: []
      }

      transactions: {
        Row: {
          id: string
          workspace_id: string
          account_id: string
          category_id: string | null
          counterparty_account_id: string | null
          type: string
          amount: number
          description: string | null
          occurred_on: string
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          workspace_id: string
          account_id: string
          category_id?: string | null
          counterparty_account_id?: string | null
          type: string
          amount: number
          description?: string | null
          occurred_on?: string
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          workspace_id?: string
          account_id?: string
          category_id?: string | null
          counterparty_account_id?: string | null
          type?: string
          amount?: number
          description?: string | null
          occurred_on?: string
          created_at?: string
          updated_at?: string
        }
        Relationships: []
      }

      workspace_members: {
        Row: {
          workspace_id: string
          user_id: string
          role: string
          created_at: string
        }
        Insert: {
          workspace_id: string
          user_id: string
          role?: string
          created_at?: string
        }
        Update: {
          workspace_id?: string
          user_id?: string
          role?: string
          created_at?: string
        }
        Relationships: []
      }

      workspaces: {
        Row: {
          id: string
          name: string
          kind: string
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          name: string
          kind?: string
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          name?: string
          kind?: string
          created_at?: string
          updated_at?: string
        }
        Relationships: []
      }
    }

    Views: {
      workspace_totals: {
        Row: {
          workspace_id: string
          total_income: number
          total_expense: number
          net_balance: number
          total_transferred: number
        }
      }
      account_balances: {
        Row: {
          workspace_id: string
          account_id: string
          name: string
          kind: string
          balance: number
        }
      }
      expense_by_category: {
        Row: {
          workspace_id: string
          category_id: string | null
          category_name: string | null
          total: number
        }
      }
    }

    Functions: Record<never, never>
    Enums: Record<never, never>
    CompositeTypes: Record<never, never>
  }
}

/** Narrow the loose `type`/`kind`/`role` text columns to their CHECK-constrained values. */
export type TransactionType = 'income' | 'expense' | 'transfer'
export type CategoryType = 'income' | 'expense'
export type AccountKind = 'cash' | 'bank' | 'mobile' | 'credit_card'
export type WorkspaceKind = 'personal' | 'business' | 'family'
export type MemberRole = 'owner' | 'member'

export type Tables<T extends keyof Database['public']['Tables']> =
  Database['public']['Tables'][T]['Row']
export type TablesInsert<T extends keyof Database['public']['Tables']> =
  Database['public']['Tables'][T]['Insert']
export type TablesUpdate<T extends keyof Database['public']['Tables']> =
  Database['public']['Tables'][T]['Update']