import type { Metadata, Viewport } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import { OfflineBanner } from '@/components/app/OfflineBanner'
import { AppleStartupImages } from './AppleStartupImages'
import './globals.css'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
  display: 'swap',
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: {
    default: 'TakaKori',
    template: '%s · TakaKori',
  },
  description: 'Track your income and expenses. Built for Bangladesh.',
  applicationName: 'TakaKori',
  appleWebApp: {
    capable: true,
    title: 'TakaKori',
    // `default` rather than `black-translucent`. The latter is the only way to
    // get a fullscreen iOS app, and fullscreen here would put the layout under
    // the status bar while `--nav-clear` assumes it is not. `viewport-fit: cover`
    // plus `env(safe-area-inset-bottom)` is the arrangement that actually keeps
    // the home indicator off the last row.
    statusBarStyle: 'default',
  },
  icons: {
    /**
     * iOS names its home-screen icon by file, and reads `apple-touch-icon` in
     * preference to the manifest. Without these, iOS 16.4+ draws a monogram of
     * the site's first letter on a colour it samples itself — and because there
     * is no `apple-touch-icon`, it falls through to the manifest's SVG, which
     * older iOS releases do not use for this purpose at all.
     *
     * Generated by `npm run icons`; see that script for why these are
     * full-bleed rather than copies of `icon.svg`.
     */
    apple: [
      { url: '/icons/apple-touch-icon-180.png', sizes: '180x180', type: 'image/png' },
      { url: '/icons/apple-touch-icon-167.png', sizes: '167x167', type: 'image/png' },
      { url: '/icons/apple-touch-icon-152.png', sizes: '152x152', type: 'image/png' },
      { url: '/icons/apple-touch-icon-120.png', sizes: '120x120', type: 'image/png' },
    ],
  },
  formatDetection: { telephone: false },
}

export const viewport: Viewport = {
  width: 'device-width',
  initialScale: 1,
  // Zoom is pinned at 1. iOS Safari has ignored `user-scalable=no` since iOS 10,
  // so this does not stop a pinch-zoom there — what it does control is
  // double-tap-to-zoom and the Android/Chrome behaviour, both of which produce
  // the same broken half-scrolled state on a form-heavy screen.
  //
  // The real defence against the iOS zoom is that no field renders under 16px
  // (`.tk-field` in globals.css). iOS zooms the page on focus of a sub-16px
  // input and never zooms back out, which is what leaves the tab bar sitting
  // over the content. Setting this alone would look like a fix and change
  // nothing on the phone.
  //
  // Accessibility note: disabling pinch-zoom is a WCAG 1.4.4 failure. It is set
  // here because this app's layout has no content that benefits from zooming and
  // a zoomed state is genuinely unusable — but it is a real trade-off, not a
  // free win, and it should be revisited if the app ever gains dense tables or
  // long-form reading.
  maximumScale: 1,
  userScalable: false,
  // `viewport-fit=cover` is what lets the tab bar and the home indicator share
  // the bottom of the screen; the layout then pads itself with
  // `env(safe-area-inset-bottom)` so nothing hides behind the indicator.
  viewportFit: 'cover',
  // `--brand-600`. This read `#0a8a5b` until the token was darkened to clear
  // 4.5:1 for the primary button's white label, and neither copy was updated —
  // `docs/design-system.md` warns at the top about three copies of the truth
  // drifting, and this was one of them. It is now written as the same value
  // `globals.css` defines, with the reason recorded here and in `manifest.ts`.
  themeColor: '#0a8256',
}

export default function RootLayout({ children }: LayoutProps<'/'>) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}>
      <body className="flex min-h-full flex-col">
        {/* Every screen, including sign-in: losing signal matters most where a
            user taps submit and waits. First child of the body, in normal flow,
            so it pushes the page down and covers nothing. */}
        <OfflineBanner />
        <AppleStartupImages />
        {children}
      </body>
    </html>
  )
}
